baseURL = "https://alandsha.github.io/alsha-site/"
title = "Al & Sha"
languageCode = "en"
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  description = "Ideas in Motion  Design  Marketing  AI  B2B Ops"
  defaultTheme = "light"
  disableThemeToggle = true
  label = { text = "Al & Sha" }
  images = ["/images/hero.jpg"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 20
  [[menu.main]]
    name = "B2B Services"
    url = "/services/"
    weight = 30

[minify]
  disableXML = true

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe = true
[params.label]
  text = ""                 # vacío para no duplicar texto al lado del logo
  icon = "/images/alandshalogo.png"
  iconHeight = 42           # prueba 3648 según veas[params]  disableThemeToggle = true