baseURL = "https://alandsha.github.io/alsha-site/"
title = "Al & Sha"
languageCode = "en"
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  description = "Ideas in Motion  Lean B2B ops where technology meets art."
  images = ["/images/hero.jpg"]
  defaultTheme = "light"

  [params.label]
    text = ""                            # sin texto, solo el logo
    icon = "/images/alandshalogo.png"    # tu imagen
    iconHeight = 44                      # altura del logo en la cabecera

[menu]
  [[menu.main]] name = "Home"     url = "/"          weight = 10
  [[menu.main]] name = "Contact"  url = "/contact/"  weight = 20
  [[menu.main]] name = "Services" url = "/services/" weight = 30

[minify]
  disableXML = true

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe = true
