baseURL = "https://al-sha.com/"
title = "Al & Sha"
languageCode = "en"
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  description = "Automation and clarity for small teams."
  defaultTheme = "light"
  images = ["/images/hero.jpg"]

  [params.label]
    text = ""                          # oculta texto textual
    icon = "/images/alandshalogo.png"  # logo
    iconHeight = 64                    # tama√±o logo

[menu]
  [[menu.main]] name = "Services" url = "/services/" weight = 10
  [[menu.main]] name = "Contact"  url = "/contact/"  weight = 20

[minify]
  disableXML = true
[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"
[permalinks]
  posts = "/:slug/"
[markup.goldmark.renderer]
  unsafe = true