baseURL = "https://www.al-sha.com/"
title = "Al & Sha"
languageCode = "en"
theme = "PaperMod"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
pagerSize = 10

[params]
defaultTheme = "light"

[params.label]
text = ""
icon = "/images/alandshalogo.png"
iconHeight = 36

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 10
  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 20